import type { ParsedDafWorkbook } from './types.js';

export const DEFAULT_DAF_PARSED_WORKBOOK = {
  "fileName": "DAF - Logic Matrix - In Progress.xlsx",
  "sheetNames": [
    "Logic Matrix",
    "Request Types",
    "Daily Action Fields",
    "Action Values",
    "Evaluation Order",
    "Sources"
  ],
  "logicRows": [
    {
      "ruleId": "R001",
      "ruleGroup": "Pre-processing",
      "business": "All",
      "requestTypes": "All",
      "decisionCriteria": "Vendor in Baldor, Network, UNFI, Vesta, Vistar Vending, The Chefs Warehouse, Gourmet",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Vendor",
      "setAction": "Remove from working copy / do not process managed workflow",
      "downstreamHandling": "",
      "discoveryReference": "Daily Sheet Action Process 7-13; Splitting Process 16-21",
      "notes": "Needs managed-vendor list confirmation",
      "sourceRowNumber": 3
    },
    {
      "ruleId": "R002",
      "ruleGroup": "Pre-processing",
      "business": "All",
      "requestTypes": "All",
      "decisionCriteria": "MIN is blank OR DIN is blank",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "MIN; DIN",
      "setAction": "Invalid Information",
      "downstreamHandling": "Specialist/manual review",
      "discoveryReference": "Daily Sheet Action Process 93",
      "notes": "Direct row-level validation",
      "sourceRowNumber": 4
    },
    {
      "ruleId": "R003",
      "ruleGroup": "Business branch",
      "business": "FoodbuyOne",
      "requestTypes": "All",
      "decisionCriteria": "if VA >=10%, S1, Diverse, or Front of House; if not contracted use Find Alt 1st; 1X approved and email Imogen",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Business; Meets Criteria; Compass APL; Parent/Sub Category; One-Time or Permanent",
      "setAction": "Process like Compass. Approve if VA >=10%, S1, Diverse, or Front of House; if not contracted use Find Alt 1st; 1X approved and email Imogen",
      "downstreamHandling": "Notify Imogen for 1X tracking",
      "discoveryReference": "Daily Sheet Action Process 14-19",
      "notes": "Business-specific summary rule",
      "sourceRowNumber": 5
    },
    {
      "ruleId": "R004",
      "ruleGroup": "Business branch",
      "business": "HMSHost",
      "requestTypes": "All",
      "decisionCriteria": "Business = HMSHost",
      "action": "Review",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Business; ACTION",
      "setAction": "HMSHost",
      "downstreamHandling": "Route as HMSHost",
      "discoveryReference": "Daily Sheet Action Process 21-23",
      "notes": "Follow up on this rule, potential to understand downstream process.",
      "sourceRowNumber": 6
    },
    {
      "ruleId": "R005",
      "ruleGroup": "Canada Mass Add",
      "business": "Compass Canada",
      "requestTypes": "Mass Adds",
      "decisionCriteria": "IF Business = Compass Canada AND Request Type = Mass Add",
      "action": "OK",
      "ifInStockAction": "Blank",
      "buysmartAction": "Assigned",
      "dailyActionFileColumns": "Business, Request Type",
      "setAction": "Approve only Core APL or Pantry. If not Pantry/APL then NO",
      "downstreamHandling": "Keep inherited system action text where present",
      "discoveryReference": "Daily Sheet Action Process 25-32",
      "notes": "Mass add remains Assigned per closeout rule",
      "sourceRowNumber": 7
    },
    {
      "ruleId": "R006",
      "ruleGroup": "Canada PRF",
      "business": "Compass Canada",
      "requestTypes": "PRF",
      "decisionCriteria": "Business = Compass Canada AND Request Type = PRF AND S1 = TRUE OR Pantry = TRUE",
      "action": "OK",
      "ifInStockAction": "Blank",
      "buysmartAction": "Assigned",
      "dailyActionFileColumns": "Business, Request Type, Compass APL, Pantry",
      "setAction": "Check if use right is APL; for 1X usage <10 comment may approve requested 1X if use right is not APL",
      "downstreamHandling": "Manual APL/use-right validation",
      "discoveryReference": "Daily Sheet Action Process 27-28, 42-43, 288",
      "notes": "Needs external APL validation",
      "sourceRowNumber": 8
    },
    {
      "ruleId": "R006",
      "ruleGroup": "Canada PRF",
      "business": "Compass Canada",
      "requestTypes": "PRF",
      "decisionCriteria": "Business = Compass Canada AND Request Type = PRF AND S1 = TRUE OR Pantry = TRUE",
      "action": "Cannot Add/Not In-Stock",
      "ifInStockAction": "OK",
      "buysmartAction": "Assigned",
      "dailyActionFileColumns": "Business, Request Type, Compass APL, Pantry",
      "setAction": "Check if use right is APL; for 1X usage <10 comment may approve requested 1X if use right is not APL",
      "downstreamHandling": "Manual APL/use-right validation",
      "discoveryReference": "Daily Sheet Action Process 27-28, 42-43, 288",
      "notes": "Needs external APL validation",
      "sourceRowNumber": 9
    },
    {
      "ruleId": "R007",
      "ruleGroup": "Canada 1X",
      "business": "Compass Canada",
      "requestTypes": "PRF, SORF, SRF",
      "decisionCriteria": "Business = Compass Canada AND One-Time or Permanent = One-Time AND Usage <= 10 AND not APL/S1/Pantry",
      "action": "OK",
      "ifInStockAction": "OK",
      "buysmartAction": "Assigned",
      "dailyActionFileColumns": "Business; One-Time or Permanent; Usage; Compass APL; Pantry",
      "setAction": "1X",
      "downstreamHandling": "Approve as one-time",
      "discoveryReference": "Daily Sheet Action Process 33-41",
      "notes": "Email comms today are sent manually, potentially an opportunity to auto-gen an email in the future. Maybe a \"report template\"",
      "sourceRowNumber": 10
    },
    {
      "ruleId": "R008",
      "ruleGroup": "Canada 1X escalation",
      "business": "Compass Canada",
      "requestTypes": "PRF, SORF, SRF",
      "decisionCriteria": "Business = Compass Canada AND One-Time or Permanent = One-Time AND Usage > 10 AND not APL/S1/Pantry",
      "action": "OK",
      "ifInStockAction": "OK",
      "buysmartAction": "Review",
      "dailyActionFileColumns": "Business; One-Time or Permanent; Usage; Compass APL; Pantry",
      "setAction": "Escalate to Betty MacDonald and Joy Pereira",
      "downstreamHandling": "Ask which cases can be approved",
      "discoveryReference": "Daily Sheet Action Process 34-35",
      "notes": "Review required by compliance team for usage X>10",
      "sourceRowNumber": 11
    },
    {
      "ruleId": "R009",
      "ruleGroup": "HealthTrust SRF",
      "business": "HealthTrust",
      "requestTypes": "SRF",
      "decisionCriteria": "Business = HealthTrust AND Type = SRF AND item is S1, Passport, Evergood, Medtrition, or contracted with VA >=10% and no better S1 alternative",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Business; Type; Compass APL; Manufacturer; Meets Criteria; Conversion DIN",
      "setAction": "OK or Check for S1 alt, if there isn't one, please approve",
      "downstreamHandling": "Specialist handles as SRF",
      "discoveryReference": "Daily Sheet Action Process 51-56",
      "notes": "*Follow up on this rule - understand if hard rule vs. conditional using other inputs Requires external alternative check for contracted 10%+",
      "sourceRowNumber": 12
    },
    {
      "ruleId": "R010",
      "ruleGroup": "HealthTrust SRF",
      "business": "HealthTrust",
      "requestTypes": "SRF",
      "decisionCriteria": "Business = HealthTrust AND Type = SRF AND not preferred/S1/10% + contracted (VA = any %)",
      "action": "Check w/CDM",
      "ifInStockAction": "",
      "buysmartAction": "Assigned",
      "dailyActionFileColumns": "Business; Type; Compass APL; Meets criteria",
      "setAction": "NO",
      "downstreamHandling": "CS to connect with CDM",
      "discoveryReference": "Daily Sheet Action Process 55",
      "notes": "",
      "sourceRowNumber": 13
    },
    {
      "ruleId": "R011",
      "ruleGroup": "HealthTrust PRF/SORF conversion",
      "business": "HealthTrust",
      "requestTypes": "PRF",
      "decisionCriteria": "Business = HealthTrust AND Type in PRF AND Conversion DIN is not blank",
      "action": "Use Right",
      "ifInStockAction": "",
      "buysmartAction": "Assigned",
      "dailyActionFileColumns": "Business; Type; Conversion DIN",
      "setAction": "Use Right",
      "downstreamHandling": "Use conversion item",
      "discoveryReference": "Daily Sheet Action Process 57-60",
      "notes": "Use Right -- ability to check if \"in-stock\" would be a value add",
      "sourceRowNumber": 14
    },
    {
      "ruleId": "R014",
      "ruleGroup": "HealthTrust PRF/SORF conversion",
      "business": "HealthTrust",
      "requestTypes": "SORF",
      "decisionCriteria": "Business = HealthTrust AND Type in SORF AND Conversion DIN is not blank AND usage is below 10 cases",
      "action": "Use Right",
      "ifInStockAction": "",
      "buysmartAction": "Review",
      "dailyActionFileColumns": "Business; Type; Conversion DIN; Usage (column X)",
      "setAction": "Use Right",
      "downstreamHandling": "Use conversion item",
      "discoveryReference": "Daily Sheet Action Process 57-60",
      "notes": "*Follow up, may need adjustment to rule Use Right -- ability to check if \"in-stock\" would be a value add",
      "sourceRowNumber": 15
    },
    {
      "ruleId": "R012",
      "ruleGroup": "HealthTrust PRF/SORF approval",
      "business": "HealthTrust",
      "requestTypes": "PRF",
      "decisionCriteria": "Business = HealthTrust AND Type is PRF AND S1/Diverse/FOH OR Pantry OR Meets Criteria >=10%",
      "action": "OK",
      "ifInStockAction": "",
      "buysmartAction": "Assigned",
      "dailyActionFileColumns": "Compass APL; Pantry; Meets Criteria; One-Time or Permanent",
      "setAction": "OK for Permanent",
      "downstreamHandling": "Specialist handles as PRF",
      "discoveryReference": "Daily Sheet Action Process 62-74",
      "notes": "",
      "sourceRowNumber": 16
    },
    {
      "ruleId": "R012",
      "ruleGroup": "HealthTrust PRF/SORF approval",
      "business": "HealthTrust",
      "requestTypes": "SORF",
      "decisionCriteria": "Business = HealthTrust AND Type is SORF AND S1/Diverse/FOH OR Pantry OR Meets Criteria >=10%",
      "action": "OK",
      "ifInStockAction": "",
      "buysmartAction": "Approved",
      "dailyActionFileColumns": "Compass APL; Pantry; Meets Criteria; One-Time or Permanent",
      "setAction": "OK for Permanent",
      "downstreamHandling": "Specialist handles as PRF",
      "discoveryReference": "Daily Sheet Action Process 62-74",
      "notes": "",
      "sourceRowNumber": 17
    },
    {
      "ruleId": "R012",
      "ruleGroup": "HealthTrust PRF/SORF approval",
      "business": "HealthTrust",
      "requestTypes": "SORF",
      "decisionCriteria": "Business = HealthTrust AND Type is SORF AND IS NOT S1/Diverse/FOH OR Pantry OR Does Not Meet Criteria <=10%",
      "action": "Review",
      "ifInStockAction": "",
      "buysmartAction": "Assigned",
      "dailyActionFileColumns": "Compass APL; Pantry; Meets Criteria; One-Time or Permanent",
      "setAction": "Review",
      "downstreamHandling": "Specialist handles as SORF",
      "discoveryReference": "Daily Sheet Action Process 62-74",
      "notes": "",
      "sourceRowNumber": 18
    },
    {
      "ruleId": "R013",
      "ruleGroup": "HealthTrust PRF/SORF review",
      "business": "HealthTrust",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "Meets Criteria <10% or blank AND not preferred/pantry",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Usage; Description; Brand; Parent Category; Sub Category",
      "setAction": "1X for acceptable one-time; NO / Find Alt 1st / Check with CDM for high-risk categories or high usage",
      "downstreamHandling": "Manual category review",
      "discoveryReference": "Daily Sheet Action Process 75-94",
      "notes": "Judgment-heavy branch",
      "sourceRowNumber": 19
    },
    {
      "ruleId": "R014",
      "ruleGroup": "Compass SRF conversion",
      "business": "Compass USA",
      "requestTypes": "SRF",
      "decisionCriteria": "Business = Compass USA AND Type = SRF AND Conversion DIN is not blank",
      "action": "Use Right",
      "ifInStockAction": "",
      "buysmartAction": "Assigned",
      "dailyActionFileColumns": "Business; Type; Conversion DIN; Division; K12 APL",
      "setAction": "Use Right, except K12 conversion may be deleted and requested item approved",
      "downstreamHandling": "K12 Schools Division can trump conversion",
      "discoveryReference": "Daily Sheet Action Process 105-107",
      "notes": "K12 exception **Note: Potential to use MW data model for ingredient match, supplementing the data for alternatives, in-stock, VA%",
      "sourceRowNumber": 20
    },
    {
      "ruleId": "R015",
      "ruleGroup": "Compass SRF",
      "business": "Compass USA",
      "requestTypes": "SRF",
      "decisionCriteria": "IF S1/Diverse/FOH OR K12 Schools on K12 APL OR Sweet Streets/Evergood/Passport/Medtrition OR contracted VA >=10% = TRUE",
      "action": "OK",
      "ifInStockAction": "",
      "buysmartAction": "Assigned",
      "dailyActionFileColumns": "Compass APL; K12 APL; Division; Manufacturer; Meets Criteria; In CAT",
      "setAction": "OK or Check for S1 alt, if no alt found - deny",
      "downstreamHandling": "If in catalog but not On MOG: In stock - approve as PRF",
      "discoveryReference": "Daily Sheet Action Process 108-115",
      "notes": "Catalog visibility affects secondary action",
      "sourceRowNumber": 21
    },
    {
      "ruleId": "R015",
      "ruleGroup": "Compass SRF",
      "business": "Compass USA",
      "requestTypes": "SRF",
      "decisionCriteria": "IF S1/Diverse/FOH OR K12 Schools on K12 APL OR Sweet Streets/Evergood/Passport/Medtrition OR contracted VA >=10% = FALSE",
      "action": "Check w/CDM",
      "ifInStockAction": "",
      "buysmartAction": "Assigned",
      "dailyActionFileColumns": "Compass APL; K12 APL; Division; Manufacturer; Meets Criteria; In CAT",
      "setAction": "OK or Check for S1 alt, if no alt found - deny",
      "downstreamHandling": "If in catalog but not On MOG: In stock - approve as PRF",
      "discoveryReference": "Daily Sheet Action Process 108-115",
      "notes": "Catalog visibility affects secondary action",
      "sourceRowNumber": 22
    },
    {
      "ruleId": "R016",
      "ruleGroup": "Seasonal request",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "Sector/Business indicates Levy AND Reason for request contains Sponsorship Item",
      "action": "OK",
      "ifInStockAction": "",
      "buysmartAction": "Assigned",
      "dailyActionFileColumns": "Sector; Reason for request; Manufacturer",
      "setAction": "OK or 1X based on one-time/permanent",
      "downstreamHandling": "Approve seasonal exception",
      "discoveryReference": "Daily Sheet Action Process 118-119",
      "notes": "Doc says must be Levy",
      "sourceRowNumber": 23
    },
    {
      "ruleId": "R016",
      "ruleGroup": "Seasonal request",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "Request = PRF or SORF AND Reason for request contains MenuCycle",
      "action": "OK",
      "ifInStockAction": "",
      "buysmartAction": "Assigned",
      "dailyActionFileColumns": "Sector; Reason for request; Manufacturer",
      "setAction": "OK or 1X based on one-time/permanent",
      "downstreamHandling": "Approve seasonal exception",
      "discoveryReference": "Daily Sheet Action Process 118-119",
      "notes": "Doc says must be Levy",
      "sourceRowNumber": 24
    },
    {
      "ruleId": "R017",
      "ruleGroup": "Conversion/category",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF, SRF",
      "decisionCriteria": "Sub Category or Description contains Cookie Dough AND Conversion DIN is not blank",
      "action": "Use Right",
      "ifInStockAction": "",
      "buysmartAction": "Assigned",
      "dailyActionFileColumns": "Sub Category; Description; Conversion DIN; Sector; Usage",
      "setAction": "Use Right if conversion matches cookie matrix; Check with CDM if neither requested nor conversion matches; approve requested/delete conversion if sector not on matrix and descriptions differ",
      "downstreamHandling": "Refer to cookie dough matrix",
      "discoveryReference": "Daily Sheet Action Process 121-131, 193-195",
      "notes": "Cookie Matrix - Potential for this data to be fluid, or updated on a cadence (IE, annually, quarterly, bi-annually, etc.) **Note for Impower - if users need to update this matrix, where does it live?",
      "sourceRowNumber": 25
    },
    {
      "ruleId": "R018",
      "ruleGroup": "Conversion/category",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF, SRF",
      "decisionCriteria": "Sub Category = Chicken Breast Unbreaded Raw and item is 4 oz or 5 oz",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Sub Category; Description; Pack; Division",
      "setAction": "Use MIN _____ - (MFR) or Send to CDM",
      "downstreamHandling": "Use BSB DCs by Supplier matrix",
      "discoveryReference": "Daily Sheet Action Process 66-67, 134-135, 196-202",
      "notes": "External matrix required",
      "sourceRowNumber": 26
    },
    {
      "ruleId": "R019",
      "ruleGroup": "Conversion/category",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF, SRF",
      "decisionCriteria": "Sub Category = Pork Bacon",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Sub Category; Brand; Manufacturer; Meets Criteria; Sector",
      "setAction": "Use MIN _____ - (MFR), Find Alt 1st, NO, or OK for specific exceptions",
      "downstreamHandling": "Use Recommended Bacon SKU per DC matrix; Smithfield preferred; BA can have Clemmons",
      "discoveryReference": "Daily Sheet Action Process 136-137, 180-183",
      "notes": "External matrix and sector exception",
      "sourceRowNumber": 27
    },
    {
      "ruleId": "R020",
      "ruleGroup": "Conversion/category",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF, SRF",
      "decisionCriteria": "Division = Schools Division AND requested item is on K12 APL, high VA, On MOG, S1, or preferred manufacturer",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Division; K12 APL; Meets Criteria; On MOG; Compass APL; Manufacturer",
      "setAction": "Delete conversion and approve requested as OK or 1X",
      "downstreamHandling": "Requested item trumps conversion",
      "discoveryReference": "Daily Sheet Action Process 138-139",
      "notes": "K12-specific override",
      "sourceRowNumber": 28
    },
    {
      "ruleId": "R021",
      "ruleGroup": "Conversion/category",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF, SRF",
      "decisionCriteria": "Reason for request contains Sponsorship, Allocation, or Commodity",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Reason for request; Conversion DIN",
      "setAction": "Approve requested and remove Conversion DIN",
      "downstreamHandling": "Exception approval",
      "discoveryReference": "Daily Sheet Action Process 144",
      "notes": "Schools commodity/allocation context noted",
      "sourceRowNumber": 29
    },
    {
      "ruleId": "R022",
      "ruleGroup": "Conversion/category",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF, SRF",
      "decisionCriteria": "One-Time or Permanent = One-Time AND Usage < 15 AND Conversion DIN is not blank",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "One-Time or Permanent; Usage; Conversion DIN",
      "setAction": "Approve requested as 1X and remove Conversion DIN",
      "downstreamHandling": "One-time low usage exception",
      "discoveryReference": "Daily Sheet Action Process 145",
      "notes": "Threshold under 15",
      "sourceRowNumber": 30
    },
    {
      "ruleId": "R023",
      "ruleGroup": "Compass APL",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "Compass APL is S1, FOH, Diverse Supplier, or Core APL",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Compass APL; One-Time or Permanent; ACTION",
      "setAction": "1X for One-Time; OK for Permanent; preserve On MOG/Cannot Add and put OK in If In Stock",
      "downstreamHandling": "Approve requested",
      "discoveryReference": "Daily Sheet Action Process 149-158",
      "notes": "Core approval branch",
      "sourceRowNumber": 31
    },
    {
      "ruleId": "R024",
      "ruleGroup": "K12 APL",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "Division = Schools Division AND K12 APL = Y",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Division; K12 APL; One-Time or Permanent",
      "setAction": "1X for One-Time; OK for Permanent",
      "downstreamHandling": "Automatic approval for Chartwells Schools Division only",
      "discoveryReference": "Daily Sheet Action Process 161-162",
      "notes": "Scope limited to Chartwells Schools",
      "sourceRowNumber": 32
    },
    {
      "ruleId": "R025",
      "ruleGroup": "Pantry",
      "business": "All",
      "requestTypes": "PRF, SORF, Mass Adds",
      "decisionCriteria": "Pantry is Item or Subcategory",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Pantry; One-Time or Permanent",
      "setAction": "1X for One-Time; OK for Permanent",
      "downstreamHandling": "Approve pantry",
      "discoveryReference": "Daily Sheet Action Process 45, 68-73, 163-164",
      "notes": "Pantry approval signal",
      "sourceRowNumber": 33
    },
    {
      "ruleId": "R026",
      "ruleGroup": "VA threshold",
      "business": "Compass USA, HealthTrust, FoodbuyOne",
      "requestTypes": "PRF, SORF, SRF",
      "decisionCriteria": "Meets Criteria >= 10%",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Meets Criteria; One-Time or Permanent",
      "setAction": "1X for One-Time; OK for Permanent, unless external S1 alt check required",
      "downstreamHandling": "Daily Sheet Action Process 17, 54, 71-74, 112, 165-169",
      "discoveryReference": "High",
      "notes": "",
      "sourceRowNumber": 34
    },
    {
      "ruleId": "R027",
      "ruleGroup": "Reason exception",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "Reason for request contains Sponsorship, Commodity, or Allocation",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Reason for request; Division",
      "setAction": "OK or 1X based on one-time/permanent",
      "downstreamHandling": "Sponsorship/commodity/allocation approval exception",
      "discoveryReference": "Daily Sheet Action Process 171-174",
      "notes": "Commodity/allocation noted for Schools Division",
      "sourceRowNumber": 35
    },
    {
      "ruleId": "R028",
      "ruleGroup": "Category exception",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "Description contains Halal OR gluten free/sugar free/vegan/kosher/gf OR nutritional/puree for Morrison",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Description; Sub Category; Sector; Division; One-Time or Permanent",
      "setAction": "OK or 1X; Check with CDM for cage-free/non-preferred 0% VA",
      "downstreamHandling": "Dietary need exception",
      "discoveryReference": "Daily Sheet Action Process 175-177, 201-207, 253-255",
      "notes": "Text-search driven",
      "sourceRowNumber": 36
    },
    {
      "ruleId": "R029",
      "ruleGroup": "Category exception",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "Sub Category contains French fries",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Sub Category; Brand; Manufacturer",
      "setAction": "OK if McCain; otherwise NO or Find McCain Alt",
      "downstreamHandling": "Preferred brand rule",
      "discoveryReference": "Daily Sheet Action Process 177-179, 266-268",
      "notes": "Lamb Weston generally not approved except listed items",
      "sourceRowNumber": 37
    },
    {
      "ruleId": "R030",
      "ruleGroup": "Category exception",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "Sub Category contains Molded Fiber",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Sub Category; Manufacturer",
      "setAction": "NO unless Huhtamaki target alternative applies",
      "downstreamHandling": "Use Huhtamaki preference",
      "discoveryReference": "Daily Sheet Action Process 184-186",
      "notes": "Preference/deny branch",
      "sourceRowNumber": 38
    },
    {
      "ruleId": "R031",
      "ruleGroup": "Category exception",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "Sub Category contains Gloves",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Sub Category; Meets Criteria; Brand",
      "setAction": "NO unless high VA and Handguards",
      "downstreamHandling": "Exception review",
      "discoveryReference": "Daily Sheet Action Process 187-188",
      "notes": "High VA exception",
      "sourceRowNumber": 39
    },
    {
      "ruleId": "R032",
      "ruleGroup": "Category exception",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "Parent Category contains Eggs",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Parent Category; Description; Usage; Meets Criteria; Manufacturer",
      "setAction": "Approve cage-free shell/liquid eggs; low usage 1X approved; otherwise Check with CDM for 0% VA/non-preferred",
      "downstreamHandling": "Cage-free rule",
      "discoveryReference": "Daily Sheet Action Process 189-192, 291-292",
      "notes": "Category-specific",
      "sourceRowNumber": 40
    },
    {
      "ruleId": "R033",
      "ruleGroup": "Category exception",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "Sub Category = Soup Frozen",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Sub Category; Brand; Manufacturer; Meets Criteria",
      "setAction": "NO unless Chef Francisco on soup MIN list; Campbells Frozen Soup 15% VA = Check with CDM",
      "downstreamHandling": "Soup MIN list review",
      "discoveryReference": "Daily Sheet Action Process 214-216, 293-295",
      "notes": "External list required",
      "sourceRowNumber": 41
    },
    {
      "ruleId": "R034",
      "ruleGroup": "Category exception",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "Sub Category contains Fresh fish OR Parent/Sub Category is vegetable/fruit fresh",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Parent Category; Sub Category; Sector",
      "setAction": "Fresh fish OK only for CCL; otherwise NO. Vegetable or Fruit = Produce MOG",
      "downstreamHandling": "Produce MOG route",
      "discoveryReference": "Daily Sheet Action Process 217-219, 289-290",
      "notes": "Sector exception",
      "sourceRowNumber": 42
    },
    {
      "ruleId": "R035",
      "ruleGroup": "Manufacturer exception",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "Manufacturer/Brand in approved list",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Manufacturer; Brand; Sector; Division",
      "setAction": "OK or 1X unless high usage/0% VA needs CDM",
      "downstreamHandling": "Approved list: Great Lakes, Sara Lee Frozen, UPROOT, Evergood, Diversey, Passport, European Imports, Woodlands Foods, Butterball, Bob's Red Mill, Zero Acres Farms, Path Water; Ballard only Morrison",
      "discoveryReference": "Daily Sheet Action Process 221-259",
      "notes": "List should be maintained as reference table",
      "sourceRowNumber": 43
    },
    {
      "ruleId": "R036",
      "ruleGroup": "1X review",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "One-Time or Permanent = One-Time AND Usage < 15 AND no glaring deny category",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "One-Time or Permanent; Usage; Parent Category; Sub Category; Manufacturer; Meets Criteria",
      "setAction": "1X",
      "downstreamHandling": "Approve low usage 1X by discretion",
      "discoveryReference": "Daily Sheet Action Process 269-272",
      "notes": "Doc uses judgment language",
      "sourceRowNumber": 44
    },
    {
      "ruleId": "R037",
      "ruleGroup": "1X escalation",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "One-Time or Permanent = One-Time AND Usage >= 15 AND Meets Criteria = 0 or low",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "One-Time or Permanent; Usage; Meets Criteria",
      "setAction": "Check with CDM or Find Alt 1st",
      "downstreamHandling": "Manual review",
      "discoveryReference": "Daily Sheet Action Process 269-271",
      "notes": "Threshold 15+",
      "sourceRowNumber": 45
    },
    {
      "ruleId": "R038",
      "ruleGroup": "Permanent review",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "One-Time or Permanent = Permanent AND ACTION is Cannot Add or On MOG",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "One-Time or Permanent; ACTION; Usage; Meets Criteria; Manufacturer",
      "setAction": "Keep inherited ACTION unless changed; If In Stock Action = OK/NO based on usage, manufacturer, VA",
      "downstreamHandling": "Item-by-item review",
      "discoveryReference": "Daily Sheet Action Process 274-279, 296",
      "notes": "Secondary action required",
      "sourceRowNumber": 46
    },
    {
      "ruleId": "R039",
      "ruleGroup": "Permanent review",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "One-Time or Permanent = Permanent AND ACTION blank AND Usage >=15",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "One-Time or Permanent; ACTION; Usage",
      "setAction": "Check with CDM",
      "downstreamHandling": "Manual review",
      "discoveryReference": "Daily Sheet Action Process 279-283",
      "notes": "Permanent high usage branch",
      "sourceRowNumber": 47
    },
    {
      "ruleId": "R040",
      "ruleGroup": "Permanent review",
      "business": "Compass USA",
      "requestTypes": "PRF, SORF",
      "decisionCriteria": "One-Time or Permanent = Permanent AND ACTION blank AND Usage <=15",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "One-Time or Permanent; ACTION; Usage",
      "setAction": "OK for no-alternative discretion; otherwise Find Alt 1st",
      "downstreamHandling": "Manual review",
      "discoveryReference": "Daily Sheet Action Process 282-283",
      "notes": "Judgment-heavy",
      "sourceRowNumber": 48
    },
    {
      "ruleId": "R041",
      "ruleGroup": "Mass closeout",
      "business": "Compass USA",
      "requestTypes": "PRF",
      "decisionCriteria": "Business = Compass USA AND Type = PRF AND One-Time or Permanent = Permanent AND ACTION in OK/On MOG AND In CAT = Y AND DIN not NEW",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Business; Type; One-Time or Permanent; ACTION; In CAT; DIN",
      "setAction": "No ACTION change",
      "downstreamHandling": "MyOrders upload",
      "discoveryReference": "Daily Sheet Action Process 299-310, 325",
      "notes": "Final BuySmart Action assignment",
      "sourceRowNumber": 49
    },
    {
      "ruleId": "R042",
      "ruleGroup": "Mass closeout",
      "business": "Compass USA",
      "requestTypes": "PRF",
      "decisionCriteria": "In CAT in N/TA/Temp Available AND ACTION = Cannot Add. Not in Stock",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "In CAT; ACTION",
      "setAction": "No ACTION change",
      "downstreamHandling": "Denied closeout",
      "discoveryReference": "Daily Sheet Action Process 314-318, 326",
      "notes": "Final BuySmart Action assignment",
      "sourceRowNumber": 50
    },
    {
      "ruleId": "R043",
      "ruleGroup": "Mass closeout",
      "business": "All",
      "requestTypes": "Mass Adds, Mass Adds - SRF",
      "decisionCriteria": "Type is Mass Adds or Mass Adds - SRF",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Type; Buysmart Action",
      "setAction": "No ACTION change",
      "downstreamHandling": "Assign to specialist designated by supervisor",
      "discoveryReference": "Daily Sheet Action Process 324; Splitting Process 67-72",
      "notes": "Mass adds are not auto-closed",
      "sourceRowNumber": 51
    },
    {
      "ruleId": "R044",
      "ruleGroup": "Mass closeout",
      "business": "All",
      "requestTypes": "All",
      "decisionCriteria": "Buysmart Action is blank after approved/denied rules",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Buysmart Action",
      "setAction": "No ACTION change",
      "downstreamHandling": "Split to specialist",
      "discoveryReference": "Daily Sheet Action Process 320-323",
      "notes": "Catch-all routing",
      "sourceRowNumber": 52
    },
    {
      "ruleId": "R045",
      "ruleGroup": "SORF Standing closeout",
      "business": "All",
      "requestTypes": "SORF",
      "decisionCriteria": "SORF Standing; Supply Chain in stock vs not stocked",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Type; In CAT/stock status; ACTION",
      "setAction": "If in stock and first-time attribute add to supply chain as PRF; if not stocked add to supply chain as SORF Standing",
      "downstreamHandling": "Final Compliance: PRF approved or SORF Standing approved; email unit/DC",
      "discoveryReference": "Action-SORF Standing 2-35",
      "notes": "Downstream after row approval",
      "sourceRowNumber": 53
    },
    {
      "ruleId": "R046",
      "ruleGroup": "SORF 1X closeout",
      "business": "All",
      "requestTypes": "SORF",
      "decisionCriteria": "SORF 1X; Supply Chain in stock vs not stocked",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Type; In CAT/stock status; ACTION",
      "setAction": "If in stock do not add to supply chain as PRF 1X; if not stocked add to supply chain as SORF 1X",
      "downstreamHandling": "Final Compliance: Approved 1x; add PRF 1X to Weekly PRF 1X sheet",
      "discoveryReference": "Action-SORF 1X 2-34",
      "notes": "Downstream after row approval",
      "sourceRowNumber": 54
    },
    {
      "ruleId": "R047",
      "ruleGroup": "PRF 1X closeout",
      "business": "All",
      "requestTypes": "PRF",
      "decisionCriteria": "ACTION = 1X or One-Time approved",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Case#; Unit Number; DST/DSTDIN; DIN; MIN; Brand; Description; Pack; Usage",
      "setAction": "Final Compliance Input A-Requested Item; Decision Approved 1x",
      "downstreamHandling": "Email DC, complete case, log to Weekly Off MOG PRF 1X sheet",
      "discoveryReference": "How to Process a PRF 1X 2-178",
      "notes": "Downstream closeout/logging",
      "sourceRowNumber": 55
    },
    {
      "ruleId": "R048",
      "ruleGroup": "PRF Already on MOG",
      "business": "All",
      "requestTypes": "PRF",
      "decisionCriteria": "ACTION = On MOG. Check Attribute OR sector already attributed on MyOrders",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "ACTION; On MOG; Sector",
      "setAction": "A-Requested Item-Already on MOG",
      "downstreamHandling": "Complete unit email; root cause Product Request Form / Already on MOG",
      "discoveryReference": "Action-PRF-AlreadyOnMOG 2-19",
      "notes": "Closeout resolution mapping",
      "sourceRowNumber": 56
    },
    {
      "ruleId": "R049",
      "ruleGroup": "Splitting",
      "business": "All",
      "requestTypes": "PRF, Mass Adds",
      "decisionCriteria": "Type in PRF or Mass Adds",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Type; Buysmart Action; Request Assignee",
      "setAction": "No ACTION change",
      "downstreamHandling": "Paste into PRF Heading Template; split Assigned non-Mass Add evenly",
      "discoveryReference": "Splitting Process 41-55",
      "notes": "Operational routing",
      "sourceRowNumber": 57
    },
    {
      "ruleId": "R050",
      "ruleGroup": "Splitting",
      "business": "All",
      "requestTypes": "SORF, SRF, Mass Adds - SRF",
      "decisionCriteria": "Type in SORF, SRF, or Mass Adds - SRF",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Type; Buysmart Action; Request Assignee",
      "setAction": "No ACTION change",
      "downstreamHandling": "Paste into SORF-SRF Heading Template; MG Foods goes to Vance",
      "discoveryReference": "Splitting Process 46-57",
      "notes": "Operational routing",
      "sourceRowNumber": 58
    },
    {
      "ruleId": "R051",
      "ruleGroup": "Upload",
      "business": "All",
      "requestTypes": "Approved rows",
      "decisionCriteria": "Buysmart Action = Approved",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "DST; DIN; Supply Chain Comment; Vendor; Usage; Meets Criteria",
      "setAction": "No ACTION change",
      "downstreamHandling": "MyOrders upload; then Supply Chain upload for approved items not already MMM",
      "discoveryReference": "Splitting Process 171-261",
      "notes": "Post-evaluation workflow",
      "sourceRowNumber": 59
    },
    {
      "ruleId": "R052",
      "ruleGroup": "Upload exception",
      "business": "All",
      "requestTypes": "Approved rows",
      "decisionCriteria": "Stock Status = Not Stocked after upload",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Stock Status; Buysmart Action",
      "setAction": "Cannot Add. Not in Stock / denial path",
      "downstreamHandling": "Remove from MyOrders and Supply Chain; send denied email",
      "discoveryReference": "Splitting Process 259-262",
      "notes": "Post-upload correction",
      "sourceRowNumber": 60
    },
    {
      "ruleId": "R053",
      "ruleGroup": "Usage email",
      "business": "All",
      "requestTypes": "Approved rows",
      "decisionCriteria": "Buysmart Action = Approved AND Usage >=15 AND Vendor is US Foods or GFS",
      "action": "",
      "ifInStockAction": "",
      "buysmartAction": "",
      "dailyActionFileColumns": "Vendor; Usage; Buysmart Action",
      "setAction": "No ACTION change",
      "downstreamHandling": "Send DC PRF email; Sysco excluded",
      "discoveryReference": "Splitting Process 265-268",
      "notes": "Post-upload notification",
      "sourceRowNumber": 61
    }
  ],
  "requestTypes": [],
  "dailyActionFields": [],
  "actionValues": [],
  "evaluationOrder": [],
  "sources": [],
  "warnings": []
} satisfies ParsedDafWorkbook;
